spring:
  application:
    name: organization-service

server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  hibernate.ddl-auto: update
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java.version: @java.version@
